name: 'Dockerfile Service Discovery & Screenshot'
description: 'Automatically discover services from Dockerfiles and capture screenshots across different viewports'
author: 'Cdaprod'

branding:
  icon: 'search'
  color: 'blue'

inputs:
  base-dir:
    description: 'Base directory to scan for Dockerfiles'
    required: false
    default: '.'
  
  screenshot-dir:
    description: 'Directory to store screenshots'
    required: false
    default: 'public/assets/screenshots'
  
  services:
    description: 'JSON string of services to scan (overrides automatic discovery)'
    required: false
  
  service-url:
    description: 'Single service URL to scan'
    required: false
  
  viewports:
    description: 'JSON array of viewport configurations'
    required: false
    default: '[{"width":1920,"height":1080,"name":"desktop"},{"width":768,"height":1024,"name":"tablet"},{"width":375,"height":812,"name":"mobile"}]'
  
  timeout:
    description: 'Timeout in milliseconds for service discovery'
    required: false
    default: '30000'
  
  wait-for-service:
    description: 'Time in seconds to wait for services to be ready'
    required: false
    default: '30'
  
  force-refresh:
    description: 'Force refresh all screenshots'
    required: false
    default: 'false'
  
  commit-screenshots:
    description: 'Whether to commit screenshots back to the repository'
    required: false
    default: 'false'
  
  generate-metadata:
    description: 'Generate metadata files for discovered services'
    required: false
    default: 'true'

outputs:
  services:
    description: 'JSON array of discovered services'
  
  screenshots:
    description: 'JSON array of generated screenshot paths'
  
  metadata-path:
    description: 'Path to the generated metadata file'

runs:
  using: 'node16'
  main: 'dist/index.js'